### PR TITLE
fix traget typo in error message

### PR DESCRIPTION
**Pull request by simonbromberg**

### CODE REVIEW

**Comment by simonbromberg** [comment]
Any reason why this hasn't been merged yet?

**Comment by non-binary** [comment]
Likely not. I have pinged the engineering team to take a look and merge it.

**Comment by non-binary** [comment]
@simonbromberg Tooling has instructed me to create a JIRA ticket so it can be scheduled for review in the coming weeks. They will follow-up here as soon as they get to it in their sprint.

**Comment by sylank** [comment]
Hey @simonbromberg,
Sorry for the long response time. Nice catch. We will merge this PR, but we will not release it at this time (because it is a small typo change). Our next release will contain this modification as well.
Thank you for your contribution 🤝 .

**Pull request merged**
